# AgeRate Prompt Evaluation - Configuration

# Data paths
data:
  input_dataset: "05_artifacts/datasets/youtube_channel_ground_truth.csv"
  enriched_dataset: "05_artifacts/datasets/youtube_channel_ground_truth_enriched.csv"
  evaluation_dataset: "05_artifacts/datasets/gold_dataset.jsonl"
  cache_directory: "cache/youtube_api"

# API settings
api:
  youtube:
    max_calls_per_day: 9000
    max_calls_per_minute: 2500
    cache_expiry_hours: 24
  openai:
    engine: "gpt-3.5-turbo-instruct"
    max_tokens: 300

# Evaluation settings
evaluation:
  default_variant: "v11_enriched"
  available_variants:
    - "v1_baseline"
    - "v2_detailed" 
    - "v3_concise"
    - "v4_structured"
    - "v5_examples"
    - "v6_chain_of_thought"
    - "v7_expert_persona"
    - "v8_minimal"
    - "v9_safety_first"
    - "v10_numeric_focus"
    - "v11_enriched"
    - "v12_criteria_based"
    - "v13_token_optimized"

# Enrichment settings
enrichment:
  test_limit_rows: 10
  production_limit_rows: null
  use_random_sampling: true
  content_analysis:
    video_sample_limit: 3
    description_truncate: 300
    title_truncate: 80

# Output settings
output:
  benchmark_directory: "04_experiments/benchmarks"
  dataset_directory: "05_artifacts/datasets"
  report_directory: "05_artifacts/reports"